// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feedURLFromID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedURLFromFeedID = `-- name: GetFeedURLFromFeedID :one
select url from feeds
where id = $1
`

func (q *Queries) GetFeedURLFromFeedID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getFeedURLFromFeedID, id)
	var url string
	err := row.Scan(&url)
	return url, err
}
