// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getFeedNameFromID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedNameFromID = `-- name: GetFeedNameFromID :one
select name from feeds
where id = $1
`

func (q *Queries) GetFeedNameFromID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getFeedNameFromID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
