// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getNextFeedToFetch.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
select id, created_at, updated_at, user_id, feed_id from feed_follows
where user_id = $1
order by updated_at nulls first
limit 1
`

func (q *Queries) GetNextFeedToFetch(ctx context.Context, userID uuid.UUID) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch, userID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
